package com.migration.service;

import org.eclipse.jgit.api.CloneCommand;
import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.transport.CredentialsProvider;
import org.eclipse.jgit.transport.PushResult;
import org.eclipse.jgit.transport.RemoteRefUpdate;
import org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.Map;

@Service
public class GitService {

    @Value("${migration.workspace.dir}")
    private String workspaceDir;

    public String cloneRepo(String repoUrl, String branch, String migrationId, String username, String password, boolean fullClone) throws Exception {
        Path workspacePath = Path.of(workspaceDir);
        Files.createDirectories(workspacePath);

        Path clonePath = workspacePath.resolve(migrationId);
        if (Files.exists(clonePath)) {
            Files.walk(clonePath)
                    .sorted(Comparator.reverseOrder())
                    .map(Path::toFile)
                    .forEach(File::delete);
        }

        CloneCommand cloneCommand = Git.cloneRepository()
                .setURI(repoUrl)
                .setDirectory(clonePath.toFile())
                .setBranch(branch)
                .setCloneAllBranches(false);

        if (!fullClone) {
            cloneCommand.setDepth(1);
        }

        if (username != null && !username.isBlank() && password != null && !password.isBlank()) {
            CredentialsProvider creds = new UsernamePasswordCredentialsProvider(username, password);
            cloneCommand.setCredentialsProvider(creds);
        }

        try (Git git = cloneCommand.call()) {
            return clonePath.toAbsolutePath().toString();
        }
    }

    public Map<String, Object> commitAndPush(String clonePath, String targetBranchName,
                                              String username, String password,
                                              int sourceVersion, int targetVersion) throws Exception {
        Map<String, Object> result = new LinkedHashMap<>();

        String branchName = targetBranchName;
        if (branchName == null || branchName.isBlank()) {
            String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"));
            branchName = "migration/jdk" + targetVersion + "-" + timestamp;
        }

        try (Git git = Git.open(new File(clonePath))) {
            git.checkout()
                    .setCreateBranch(true)
                    .setName(branchName)
                    .call();

            git.add().addFilepattern(".").call();

            var status = git.status().call();
            int changedFiles = status.getChanged().size() + status.getAdded().size()
                    + status.getModified().size() + status.getRemoved().size();

            if (changedFiles == 0) {
                result.put("pushed", false);
                result.put("branch", branchName);
                result.put("message", "No changes detected after migration. Nothing to push.");
                result.put("changedFiles", 0);
                return result;
            }

            git.commit()
                    .setMessage("chore: migrate from OpenJDK " + sourceVersion + " to OpenJDK " + targetVersion + "\n\n" +
                            "Applied OpenRewrite recipes for Java " + targetVersion + " migration.\n\n" +
                            "Generated by Java Migration Service")
                    .setAuthor("Java Migration Service", "migration@service.local")
                    .call();

            CredentialsProvider creds = null;
            if (username != null && !username.isBlank() && password != null && !password.isBlank()) {
                creds = new UsernamePasswordCredentialsProvider(username, password);
            }

            var pushCommand = git.push()
                    .setRemote("origin")
                    .add(branchName);

            if (creds != null) {
                pushCommand.setCredentialsProvider(creds);
            }

            Iterable<PushResult> pushResults = pushCommand.call();

            boolean pushSuccess = true;
            StringBuilder pushMessages = new StringBuilder();
            for (PushResult pr : pushResults) {
                for (RemoteRefUpdate update : pr.getRemoteUpdates()) {
                    RemoteRefUpdate.Status s = update.getStatus();
                    pushMessages.append(update.getRemoteName()).append(": ").append(s).append(". ");
                    if (s != RemoteRefUpdate.Status.OK && s != RemoteRefUpdate.Status.UP_TO_DATE) {
                        pushSuccess = false;
                    }
                }
            }

            result.put("pushed", pushSuccess);
            result.put("branch", branchName);
            result.put("changedFiles", changedFiles);
            result.put("message", pushSuccess
                    ? "Successfully pushed migrated code to branch: " + branchName
                    : "Push failed: " + pushMessages);

        }

        return result;
    }

    public Map<String, Object> commitAndPushNexus(String clonePath, String targetBranchName,
                                                   String username, String password,
                                                   String nexusUrl, String artifactoryUrl) throws Exception {
        Map<String, Object> result = new LinkedHashMap<>();

        String branchName = targetBranchName;
        if (branchName == null || branchName.isBlank()) {
            String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"));
            branchName = "nexus-to-artifactory/" + timestamp;
        }

        try (Git git = Git.open(new File(clonePath))) {
            git.checkout()
                    .setCreateBranch(true)
                    .setName(branchName)
                    .call();

            git.add().addFilepattern(".").call();

            var status = git.status().call();
            int changedFiles = status.getChanged().size() + status.getAdded().size()
                    + status.getModified().size() + status.getRemoved().size();

            if (changedFiles == 0) {
                result.put("pushed", false);
                result.put("branch", branchName);
                result.put("message", "No changes detected. Nothing to push.");
                result.put("changedFiles", 0);
                return result;
            }

            git.commit()
                    .setMessage("chore: migrate Nexus repository URLs to Artifactory\n\n" +
                            "Replaced all references to:\n  " + nexusUrl + "\nwith:\n  " + artifactoryUrl + "\n\n" +
                            "Generated by Java Migration Service")
                    .setAuthor("Java Migration Service", "migration@service.local")
                    .call();

            CredentialsProvider creds = null;
            if (username != null && !username.isBlank() && password != null && !password.isBlank()) {
                creds = new UsernamePasswordCredentialsProvider(username, password);
            }

            var pushCommand = git.push().setRemote("origin").add(branchName);
            if (creds != null) pushCommand.setCredentialsProvider(creds);

            Iterable<PushResult> pushResults = pushCommand.call();

            boolean pushSuccess = true;
            StringBuilder pushMessages = new StringBuilder();
            for (PushResult pr : pushResults) {
                for (RemoteRefUpdate update : pr.getRemoteUpdates()) {
                    RemoteRefUpdate.Status s = update.getStatus();
                    pushMessages.append(update.getRemoteName()).append(": ").append(s).append(". ");
                    if (s != RemoteRefUpdate.Status.OK && s != RemoteRefUpdate.Status.UP_TO_DATE) {
                        pushSuccess = false;
                    }
                }
            }

            result.put("pushed", pushSuccess);
            result.put("branch", branchName);
            result.put("changedFiles", changedFiles);
            result.put("message", pushSuccess
                    ? "Successfully pushed changes to branch: " + branchName
                    : "Push failed: " + pushMessages);
        }

        return result;
    }

    public void cleanup(String clonePath) {
        if (clonePath == null) return;
        try {
            Path path = Path.of(clonePath);
            if (Files.exists(path)) {
                Files.walk(path)
                        .sorted(Comparator.reverseOrder())
                        .map(Path::toFile)
                        .forEach(File::delete);
            }
        } catch (Exception ignored) {}
    }
}
